#include "psnd/Kernel_Hop_Replan.h"

#include "psnd/hash_fnv1a.h"
#include "psnd/macro_utils.h"
#include "psnd/vars_list.h"

namespace PROJECT_NS {

Kernel_Hop_Replan::Kernel_Hop_Replan(std::shared_ptr<Kernel> kmodel, std::shared_ptr<Kernel> krepr)
    : Kernel("Hop_Replan"), _kmodel{std::move(kmodel)}, _krepr{std::move(krepr)} {}

const std::string Kernel_Hop_Replan::getName() { return "Kernel_Hop_Replan"; }

int Kernel_Hop_Replan::getType() const { return utils::hash(FUNCTION_NAME); }

void Kernel_Hop_Replan::setInputParam_impl(std::shared_ptr<Param> PM) {
    use_state_detection = _param->get_bool({"model.use_state_detection"}, LOC(), false);
}

void Kernel_Hop_Replan::setInputDataSet_impl(std::shared_ptr<DataSet> DS) {
    occ_nuc            = DS->def(DATA::integrator::occ_nuc);
    occ_nuc_pre_switch = DS->def(DATA::integrator::occ_nuc_pre_switch);
}

Status& Kernel_Hop_Replan::executeKernel_impl(Status& stat) {
    // State detection off -> every state's gradient is already computed,
    // nothing to fix up.
    if (!use_state_detection) return stat;
    if (stat.frozen) return stat;

    // Scan trajectories for a real hop. P is the PIMD bead count and is 1
    // under nonadiabatic dynamics, so this is effectively a single compare.
    bool hopped = false;
    for (int iP = 0; iP < Dimension::P; ++iP) {
        if (occ_nuc[iP] != occ_nuc_pre_switch[iP]) {
            hopped = true;
            break;
        }
    }
    if (!hopped) return stat;

    // A second kmodel invocation in the same step is safe under
    // Model_QMInterface: QM.run input is fully rewritten each call,
    // interface.ds is regenerated by QM.py, and interface-old.ds ends up
    // reflecting the call that actually drove dynamics. For analytical
    // models a second call is simply idempotent.
    _kmodel->executeKernel(stat);

    // Re-run krepr so rep::dE is rebuilt from the freshly written dV.
    // T/eig are unchanged (V is unchanged), so in practice only dE moves.
    _krepr->executeKernel(stat);
    return stat;
}

};  // namespace PROJECT_NS
